graphhopper:
  datareader.file: data/data.xml # OSM input file (example data)
  graph.location: graph-cache
  graph.flag_encoders: car
  profiles_ch.weightings: no
  profiles:
    - name: car
      vehicle: car
      weighting: fastest

server:
  application_connectors:
  - type: http
    port: 8989
    # for security reasons bind to localhost
    bind_host: 0.0.0.0
  admin_connectors:
  - type: http
    port: 8990
    bind_host: 0.0.0.0
